## MLP for Binary Classification

In this lab, you will use the Ionosphere data binary (two-class) classification dataset to demonstrate an MLP for binary classification.

This dataset involves predicting whether a structure is in the atmosphere or not given radar returns.

The dataset will be downloaded automatically using Pandas, but you can learn more in the links below.

[Ionosphere Dataset (csv)](https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.csv)

[Ionosphere Dataset Description (csv)](https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.names)


Your task for this is lab is to develop a Keras-based Multi-Layer Perceptron model for this data set. Remember the number of output layers is equal to the number of classes.

Following we have provided some piece of code to you while you need to complete the rest of the code on your own.



In [16]:
# Importing Libraries

# Your code to import read_csv class from pandas
from pandas import read_csv

# Your code to import train_test_split class from sklearn. Follow link https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

# Read the dataset from the path below. Store the data in a pandas dataframe named 'df'

Link to API - https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html

In [17]:
path = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/ionosphere.csv'
# Your code to read the csv from the above path.
df = read_csv(path, header=None)

See the sample dataset. Print few rows of the dataset. Use dataframe.head() method.

Link to API:  https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html

In [18]:
# Your code to print first few rows of the dataset
df.head()

0   1        2        3        4        5        6        7        8   \
0   1   0  0.99539 -0.05889  0.85243  0.02306  0.83398 -0.37708  1.00000   
1   1   0  1.00000 -0.18829  0.93035 -0.36156 -0.10868 -0.93597  1.00000   
2   1   0  1.00000 -0.03365  1.00000  0.00485  1.00000 -0.12062  0.88965   
3   1   0  1.00000 -0.45161  1.00000  1.00000  0.71216 -1.00000  0.00000   
4   1   0  1.00000 -0.02401  0.94140  0.06531  0.92106 -0.23255  0.77152   

        9   ...       25       26       27       28       29       30  \
0  0.03760  ... -0.51171  0.41078 -0.46168  0.21266 -0.34090  0.42267   
1 -0.04549  ... -0.26569 -0.20468 -0.18401 -0.19040 -0.11593 -0.16626   
2  0.01198  ... -0.40220  0.58984 -0.22145  0.43100 -0.17365  0.60436   
3  0.00000  ...  0.90695  0.51613  1.00000  1.00000 -0.20099  0.25682   
4 -0.16399  ... -0.65158  0.13290 -0.53206  0.02431 -0.62197 -0.05707   

        31       32       33  34  
0 -0.54487  0.18641 -0.45300   g  
1 -0.06288 -0.13738 -0.02447   b  
2 -0.24180  0.56045 -0.38238   g  
3  1.00000 -0.32382  1.00000   b  
4 -0.59573 -0.04608 -0.65697   g  

[5 rows x 35 columns]

Print the basic info of the dataset. Use dataframe.info() from pandas library


In [19]:
# Your code to print information about the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       351 non-null    int64  
 1   1       351 non-null    int64  
 2   2       351 non-null    float64
 3   3       351 non-null    float64
 4   4       351 non-null    float64
 5   5       351 non-null    float64
 6   6       351 non-null    float64
 7   7       351 non-null    float64
 8   8       351 non-null    float64
 9   9       351 non-null    float64
 10  10      351 non-null    float64
 11  11      351 non-null    float64
 12  12      351 non-null    float64
 13  13      351 non-null    float64
 14  14      351 non-null    float64
 15  15      351 non-null    float64
 16  16      351 non-null    float64
 17  17      351 non-null    float64
 18  18      351 non-null    float64
 19  19      351 non-null    float64
 20  20      351 non-null    float64
 21  21      351 non-null    float64
 22  22

Print the shape of the dataframe. Select suitable API call from the pandas library

In [20]:
# Your code to print the shape of the dataset
df.shape

(351, 35)

# Separate the input and output from the dataframe. Input is all columns besides last column. Output is the last column.


In [21]:
X = df.values[:, :-1]
# Your code to get y - Hint y = df.values[:, some parameters]
y = df.values[:, -1]
print(X)
print(y)

[[1 0 0.99539 ... -0.54487 0.18641 -0.453]
 [1 0 1.0 ... -0.06288 -0.13738 -0.02447]
 [1 0 1.0 ... -0.2418 0.56045 -0.38238]
 ...
 [1 0 0.94701 ... 0.00442 0.92697 -0.00577]
 [1 0 0.90608 ... -0.03757 0.87403 -0.16243]
 [1 0 0.8471 ... -0.06678 0.85764 -0.06151]]
['g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b'
 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g' 'b' 'g'
 'b' '

We have converted everthing in X to 'float' and the letters in column y to the numbers in the following cell.

In [22]:
X = X.astype('float32')
y = LabelEncoder().fit_transform(y)

Printing the genral information of the X and y in the following cell

In [23]:
#LabelEncoder?
# Your code to print X
print(X)
# Your code to print y
print(y)
# your code to print shape of X. Remember X is a numpy array
print(X.shape)
# your code to print shape of y. Remember y is a numpy array
print(y.shape)

[[ 1.       0.       0.99539 ... -0.54487  0.18641 -0.453  ]
 [ 1.       0.       1.      ... -0.06288 -0.13738 -0.02447]
 [ 1.       0.       1.      ... -0.2418   0.56045 -0.38238]
 ...
 [ 1.       0.       0.94701 ...  0.00442  0.92697 -0.00577]
 [ 1.       0.       0.90608 ... -0.03757  0.87403 -0.16243]
 [ 1.       0.       0.8471  ... -0.06678  0.85764 -0.06151]]
[1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1
 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1

* Separate X and y into training and test set with a ratio of your choice.
* Print the shapes of the resulting arrays.
* Get the number of features from X_train. Remember the number of features are the number of inputs.

Use sklearn train_test_split class.
https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html


In [24]:
# Your code to separate the data into trauning and test set.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=12)

# Your code to print shape of X_train
print(X_train.shape)
# Your code to print shape of X_test
print(X_test.shape)
# Your code to print shape of y_train
print(y_train.shape)
# Your code to print shape of y_test
print(y_test.shape)

n_features = X_train.shape[1]

(245, 34)
(106, 34)
(245,)
(106,)


# Creating a Multi-layer Perceptron using Keras.
We have added first and last layers. Create the hidden layers of your choise.
You can chose any number of hidden layers and activation function of your chose
https://keras.io/api/layers/core_layers/dense/

In [25]:
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_features,)))
#
# Add as many layers with activation functions of your choice
model.add(Dense(4, activation='relu'))
#
model.add(Dense(1, activation='sigmoid'))
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 10)                350       
                                                                 
 dense_7 (Dense)             (None, 4)                 44        
                                                                 
 dense_8 (Dense)             (None, 1)                 5         
                                                                 
Total params: 399 (1.56 KB)
Trainable params: 399 (1.56 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In the next cell, we trained the above neural network model and tested its accuracy. As this concept has still not benn covered in the class, just run the code to check the accuracy.

In [26]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=1)


Epoch 1/150


8/8 [==============================] - 1s 2ms/step - loss: 0.6775 - accuracy: 0.6449
Epoch 2/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6660 - accuracy: 0.6367
Epoch 3/150
8/8 [==============================] - 0s 1ms/step - loss: 0.6550 - accuracy: 0.6367
Epoch 4/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6448 - accuracy: 0.6286
Epoch 5/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6356 - accuracy: 0.6327
Epoch 6/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6257 - accuracy: 0.6367
Epoch 7/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6173 - accuracy: 0.6367
Epoch 8/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6072 - accuracy: 0.6367
Epoch 9/150
8/8 [==============================] - 0s 2ms/step - loss: 0.5987 - accuracy: 0.6408
Epoch 10/150
8/8 [==============================] - 0s 2ms/step - loss: 0.5894 - accuracy: 0.6449
Epoch 11/150
8/8 [=========

8/8 [==============================] - 0s 869us/step - loss: 0.2041 - accuracy: 0.9184
Epoch 81/150
8/8 [==============================] - 0s 2ms/step - loss: 0.2020 - accuracy: 0.9184
Epoch 82/150
8/8 [==============================] - 0s 2ms/step - loss: 0.2005 - accuracy: 0.9184
Epoch 83/150
8/8 [==============================] - 0s 2ms/step - loss: 0.1986 - accuracy: 0.9184
Epoch 84/150
8/8 [==============================] - 0s 2ms/step - loss: 0.1964 - accuracy: 0.9184
Epoch 85/150
8/8 [==============================] - 0s 2ms/step - loss: 0.1948 - accuracy: 0.9224
Epoch 86/150
8/8 [==============================] - 0s 2ms/step - loss: 0.1930 - accuracy: 0.9224
Epoch 87/150
8/8 [==============================] - 0s 2ms/step - loss: 0.1915 - accuracy: 0.9224
Epoch 88/150
8/8 [==============================] - 0s 0s/step - loss: 0.1897 - accuracy: 0.9224
Epoch 89/150
8/8 [==============================] - 0s 0s/step - loss: 0.1882 - accuracy: 0.9224
Epoch 90/150
8/8 [===============

In [27]:
loss, acc = model.evaluate(X_test, y_test, verbose=1)
print('Test Accuracy: %.3f' % acc)

4/4 [==============================] - 0s 2ms/step - loss: 0.2439 - accuracy: 0.8868
Test Accuracy: 0.887


** How much accuracy have you got? Compare the accuracy with your peers. **
** Now, change your model and activation function to get the better accuracy as compared to your peers **

## **Important:** Document in your lab logbook the accuracy of the improved model. Do not include any code or explanations in your lab logbook. Simply record the accuracy. For example, if the obtained accuracy is 0.98, then enter "0.98" in your lab logbook.

## In addition to the accuracy, also document the output of the neural network as provided in Task 2.



Next, we have provided the code to predict on an unknown value.
We will cover these concepts later in the class. For now, just run the code to see the prediction.

In [ ]:
row = [1,0,0.99539,-0.05889,0.85243,0.02306,
       0.83398,-0.37708,1,0.03760,0.85243,-0.17755,
       0.59755,-0.44945,0.60536,-0.38223,0.84356,
       -0.38542,0.58212,-0.32192,0.56971,-0.29674,0.36946,
       -0.47357,0.56811,-0.51171,0.41078,-0.46168,0.21266,
       -0.34090,0.42267,-0.54487,0.18641,-0.45300]
yhat = model.predict([row])
print('Predicted: %.3f' % yhat)

1/1 [==============================] - 0s 77ms/step
Predicted: 0.973


In [28]:
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_features,)))
#
# Add as many layers with activation functions of your choice
model.add(Dense(20, activation='relu'))
model.add(Dense(30, activation='relu'))
model.add(Dense(40, activation='relu'))
#
model.add(Dense(1, activation='sigmoid'))
print(model.summary())

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_9 (Dense)             (None, 10)                350       
                                                                 
 dense_10 (Dense)            (None, 20)                220       
                                                                 
 dense_11 (Dense)            (None, 30)                630       
                                                                 
 dense_12 (Dense)            (None, 40)                1240      
                                                                 
 dense_13 (Dense)            (None, 1)                 41        
                                                                 
Total params: 2481 (9.69 KB)
Trainable params: 2481 (9.69 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [29]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=1)

Epoch 1/150
8/8 [==============================] - 1s 2ms/step - loss: 0.6876 - accuracy: 0.6082
Epoch 2/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6681 - accuracy: 0.6286
Epoch 3/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6458 - accuracy: 0.6408
Epoch 4/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6203 - accuracy: 0.6694
Epoch 5/150
8/8 [==============================] - 0s 2ms/step - loss: 0.5918 - accuracy: 0.7061
Epoch 6/150
8/8 [==============================] - 0s 2ms/step - loss: 0.5579 - accuracy: 0.7429
Epoch 7/150
8/8 [==============================] - 0s 2ms/step - loss: 0.5188 - accuracy: 0.7673
Epoch 8/150
8/8 [==============================] - 0s 2ms/step - loss: 0.4723 - accuracy: 0.8122
Epoch 9/150
8/8 [==============================] - 0s 3ms/step - loss: 0.4221 - accuracy: 0.8490
Epoch 10/150
8/8 [==============================] - 0s 2ms/step - loss: 0.3700 - accuracy: 0.8898
Epoch 11/150
8/8 [===========

8/8 [==============================] - 0s 2ms/step - loss: 0.0179 - accuracy: 0.9959
Epoch 85/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0175 - accuracy: 0.9959
Epoch 86/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0179 - accuracy: 0.9959
Epoch 87/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0161 - accuracy: 0.9959
Epoch 88/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0194 - accuracy: 0.9959
Epoch 89/150
8/8 [==============================] - 0s 0s/step - loss: 0.0181 - accuracy: 0.9959
Epoch 90/150
8/8 [==============================] - 0s 94us/step - loss: 0.0171 - accuracy: 0.9959
Epoch 91/150
8/8 [==============================] - 0s 612us/step - loss: 0.0145 - accuracy: 0.9959
Epoch 92/150
8/8 [==============================] - 0s 3ms/step - loss: 0.0161 - accuracy: 0.9959
Epoch 93/150
8/8 [==============================] - 0s 1ms/step - loss: 0.0143 - accuracy: 0.9959
Epoch 94/150
8/8 [=============

In [30]:
loss, acc = model.evaluate(X_test, y_test, verbose=1)
print('Test Accuracy: %.3f' % acc)

4/4 [==============================] - 0s 2ms/step - loss: 0.5952 - accuracy: 0.9245
Test Accuracy: 0.925


In [31]:
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_features,)))
#
# Add as many layers with activation functions of your choice
model.add(Dense(25, activation='relu'))
model.add(Dense(35, activation='relu'))
model.add(Dense(45, activation='relu'))
#
model.add(Dense(1, activation='sigmoid'))
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_14 (Dense)            (None, 10)                350       
                                                                 
 dense_15 (Dense)            (None, 25)                275       
                                                                 
 dense_16 (Dense)            (None, 35)                910       
                                                                 
 dense_17 (Dense)            (None, 45)                1620      
                                                                 
 dense_18 (Dense)            (None, 1)                 46        
                                                                 
Total params: 3201 (12.50 KB)
Trainable params: 3201 (12.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [32]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=1)

Epoch 1/150
8/8 [==============================] - 1s 2ms/step - loss: 0.6411 - accuracy: 0.6122
Epoch 2/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6058 - accuracy: 0.6122
Epoch 3/150
8/8 [==============================] - 0s 514us/step - loss: 0.5818 - accuracy: 0.6204
Epoch 4/150
8/8 [==============================] - 0s 252us/step - loss: 0.5580 - accuracy: 0.6653
Epoch 5/150
8/8 [==============================] - 0s 2ms/step - loss: 0.5328 - accuracy: 0.7143
Epoch 6/150
8/8 [==============================] - 0s 2ms/step - loss: 0.5071 - accuracy: 0.7673
Epoch 7/150
8/8 [==============================] - 0s 2ms/step - loss: 0.4801 - accuracy: 0.8204
Epoch 8/150
8/8 [==============================] - 0s 2ms/step - loss: 0.4461 - accuracy: 0.8531
Epoch 9/150
8/8 [==============================] - 0s 2ms/step - loss: 0.4130 - accuracy: 0.8898
Epoch 10/150
8/8 [==============================] - 0s 2ms/step - loss: 0.3755 - accuracy: 0.8939
Epoch 11/150
8/8 [=======

8/8 [==============================] - 0s 2ms/step - loss: 0.0142 - accuracy: 0.9959
Epoch 85/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0108 - accuracy: 0.9959
Epoch 86/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0117 - accuracy: 0.9959
Epoch 87/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0109 - accuracy: 0.9959
Epoch 88/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0085 - accuracy: 0.9959
Epoch 89/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0102 - accuracy: 0.9959
Epoch 90/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0078 - accuracy: 0.9959
Epoch 91/150
8/8 [==============================] - 0s 0s/step - loss: 0.0088 - accuracy: 0.9959
Epoch 92/150
8/8 [==============================] - 0s 0s/step - loss: 0.0091 - accuracy: 0.9959
Epoch 93/150
8/8 [==============================] - 0s 0s/step - loss: 0.0063 - accuracy: 0.9959
Epoch 94/150
8/8 [==================

In [33]:
loss, acc = model.evaluate(X_test, y_test, verbose=1)
print('Test Accuracy: %.3f' % acc)

4/4 [==============================] - 0s 3ms/step - loss: 0.2547 - accuracy: 0.9340
Test Accuracy: 0.934


In [34]:
model = Sequential()
model.add(Dense(10, activation='relu', input_shape=(n_features,)))
#
# Add as many layers with activation functions of your choice
model.add(Dense(35, activation='relu'))
model.add(Dense(45, activation='relu'))
model.add(Dense(55, activation='relu'))
#
model.add(Dense(1, activation='sigmoid'))
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_19 (Dense)            (None, 10)                350       
                                                                 
 dense_20 (Dense)            (None, 35)                385       
                                                                 
 dense_21 (Dense)            (None, 45)                1620      
                                                                 
 dense_22 (Dense)            (None, 55)                2530      
                                                                 
 dense_23 (Dense)            (None, 1)                 56        
                                                                 
Total params: 4941 (19.30 KB)
Trainable params: 4941 (19.30 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [35]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=150, batch_size=32, verbose=1)

Epoch 1/150
8/8 [==============================] - 1s 1ms/step - loss: 0.6878 - accuracy: 0.6245
Epoch 2/150
8/8 [==============================] - 0s 3ms/step - loss: 0.6656 - accuracy: 0.6204
Epoch 3/150
8/8 [==============================] - 0s 2ms/step - loss: 0.6367 - accuracy: 0.6286
Epoch 4/150
8/8 [==============================] - 0s 920us/step - loss: 0.6045 - accuracy: 0.6490
Epoch 5/150
8/8 [==============================] - 0s 3ms/step - loss: 0.5670 - accuracy: 0.6694
Epoch 6/150
8/8 [==============================] - 0s 2ms/step - loss: 0.5216 - accuracy: 0.7265
Epoch 7/150
8/8 [==============================] - 0s 2ms/step - loss: 0.4708 - accuracy: 0.8367
Epoch 8/150
8/8 [==============================] - 0s 2ms/step - loss: 0.4190 - accuracy: 0.8776
Epoch 9/150
8/8 [==============================] - 0s 586us/step - loss: 0.3732 - accuracy: 0.8816
Epoch 10/150
8/8 [==============================] - 0s 2ms/step - loss: 0.3336 - accuracy: 0.8898
Epoch 11/150
8/8 [=======

8/8 [==============================] - 0s 2ms/step - loss: 0.0062 - accuracy: 1.0000
Epoch 85/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0066 - accuracy: 0.9959
Epoch 86/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 87/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0056 - accuracy: 1.0000
Epoch 88/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0048 - accuracy: 1.0000
Epoch 89/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0049 - accuracy: 1.0000
Epoch 90/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 91/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 92/150
8/8 [==============================] - 0s 2ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 93/150
8/8 [==============================] - 0s 3ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 94/150
8/8 [===============

In [36]:
loss, acc = model.evaluate(X_test, y_test, verbose=1)
print('Test Accuracy: %.3f' % acc)

4/4 [==============================] - 0s 2ms/step - loss: 0.4798 - accuracy: 0.9340
Test Accuracy: 0.934


### Try out the same model with Keras Functional models!
Refer to [Keras](https://keras.io/) for more details and tutorials for the same.

In [38]:
import numpy as np
import keras

In [40]:
from keras import layers

In [41]:
inputs = keras.Input(shape=(784,))

In [42]:
img_inputs = keras.Input(shape=(32, 32, 3))

In [43]:
inputs.shape

TensorShape([None, 784])

In [44]:
inputs.dtype

tf.float32

In [45]:
dense = layers.Dense(64, activation="relu")
x = dense(inputs)

In [46]:
x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(10)(x)

In [47]:
model = keras.Model(inputs=inputs, outputs=outputs, name="mnist_model")

In [48]:
model.summary()

Model: "mnist_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 784)]             0         
                                                                 
 dense_24 (Dense)            (None, 64)                50240     
                                                                 
 dense_25 (Dense)            (None, 64)                4160      
                                                                 
 dense_26 (Dense)            (None, 10)                650       
                                                                 
Total params: 55050 (215.04 KB)
Trainable params: 55050 (215.04 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [50]:
pip install pydot

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [51]:
keras.utils.plot_model(model, "my_first_model.png")

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [52]:
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.RMSprop(),
    metrics=["accuracy"],
)

history = model.fit(x_train, y_train, batch_size=64, epochs=2, validation_split=0.2)

test_scores = model.evaluate(x_test, y_test, verbose=2)
print("Test loss:", test_scores[0])
print("Test accuracy:", test_scores[1])

11490434/11490434 [==============================] - 1s 0us/step
Epoch 1/2
750/750 [==============================] - 2s 2ms/step - loss: 0.3437 - accuracy: 0.9031 - val_loss: 0.1870 - val_accuracy: 0.9458
Epoch 2/2
750/750 [==============================] - 1s 2ms/step - loss: 0.1609 - accuracy: 0.9513 - val_loss: 0.1594 - val_accuracy: 0.9513
313/313 - 0s - loss: 0.1565 - accuracy: 0.9509 - 281ms/epoch - 898us/step
Test loss: 0.15649296343326569
Test accuracy: 0.9509000182151794
